### ISSUE TITLE
Remove unnecesary wait after stop signal is received

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airseeker-v1#161]
Currently, we wait for one more "cycle" after the stop signal is received. This is not needed, it prolongs tests and is in general annoying. We can remove it and (presumably) shorten some E2E tests.

**Comment by amarthadan** [comment]
I was working on this for some time now and I arrived at a conclusion that the suggested changes will just complicate the code (especially for tests) and won't actually bring much. Feel free to check my attempt [here](https://github.com/api3dao/airseeker/compare/remove-stop-signal-wait). It is actually nice for testing that we can somehow stop the processing.

I'm moving this to `Blocked` so you can see but I would suggest closing this as won't fix. Thoughts?

@acenolaza @vponline @Siegrift

**Comment by Siegrift** [comment]
I needed to open [a PR](https://github.com/api3dao/airseeker/pull/219) in order to leave comments. I still think it's worth doing, but I agree this is not bringing too much so we may postpone this?

**Comment by acenolaza** [comment]
I'm fine with this solution. I also find it annoying that we can't kill the process right away and I guess this mostly makes sense when testing. I'd say go for it

**Comment by amarthadan** [comment]
Yes, the `airseeker.feature.ts` test can be reworked as I outlined but what about `update-data-feeds.feature.ts`? In order to rework those you would still need to run the full Airseeker and in that case, it's pretty much the same as `airseeker.feature.ts`. Or are you suggesting just removing them?

**Comment by vponline** [comment]
> but what about update-data-feeds.feature.ts

If the goal is to remove the whole stop signal, couldn't that be done while still waiting for some (constant?) sleep time for both `airseeker.feature.ts` and `update-data-feeds.feature.ts` with a common utility function just to keep it consistent while simplifying the `main`-function?

**Comment by amarthadan** [comment]
You mean like waiting let's say 30s and then killing the process? Yes, that's basically what my solution proposes. The problem with `update-data-feeds.feature.ts` is that I would again have to run the whole Airseeker as an independent process, I can't run just specific functions.

**Comment by acenolaza** [comment]
> Yes, the `airseeker.feature.ts` test can be reworked as I outlined but what about `update-data-feeds.feature.ts`? In order to rework those you would still need to run the full Airseeker and in that case, it's pretty much the same as `airseeker.feature.ts`. Or are you suggesting just removing them?

Just removing them. In AWS or GCP this will not make much of a difference but when running locally or from e2e it will.
