### ISSUE TITLE
Remove old/unnecesary parts

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airseeker-v1#162]
Since we're not running Airseeker as a long-running service, there are parts that can be removed:
* Terraform recipes
* pm2 setup
* Docker containerization
* some helper scripts

We can (and probably should) remove these to keep the repository clean and less confusing at first sight.
@aquarat @bbenligiray What do you think about this? I'd say we should remove what we can, we can always dig it back up from the git history if needed :man_shrugging:

**Comment by bbenligiray** [comment]
Makes sense to me
