### ISSUE TITLE
Prepare config format & validation for `beaconSets` section

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airseeker-v1#163]
This section describes what beacons (array elements are beacon IDs) belong to a specific beacon set (the object keys are beacon set IDs):
```json
"beaconSets": {
  "0x924b5d4cb3ec6366ae4302a1ca6aec035594ea3ea48a102d160b50b0c43ebfb5": [
    "0x924b5d4cb3ec6366ae4302a1ca6aec035594ea3ea48a102d160b50b0c43ebfb5",
    "0x924b5d4cb3ec6366ae4302a1ca6aec035594ea3ea48a102d160b50b0c43ebfb6"
  ]
},
```
In the validation, we need to make sure that every beacon listed has its counterpart in the `beacons` section.

**Comment by bbenligiray** [comment]
What if `0x924b5d4cb3ec6366ae4302a1ca6aec035594ea3ea48a102d160b50b0c43ebfb5` is also listed under `beacons`, would it be fetched twice, independently?
It feels like my answer to [the first question here](https://api3workspace.slack.com/archives/C037NLX1R8T/p1657798004380449) was wrong and we should always list all Beacons that are being updated (individually or as a set) under `beacons`.

**Comment by amarthadan** [comment]
Issue description updated based on the [Slack discussion](https://api3workspace.slack.com/archives/C037NLX1R8T/p1658137012920379?thread_ts=1658072085.473819&cid=C037NLX1R8T).
