### ISSUE TITLE
Prepare config format & validation for `triggers.beaconSetUpdates` section

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airseeker-v1#164]
I presume this will be similar to the `triggers.beaconUpdates` section, grouped based on the chain and sponsor. Deviation threshold and heartbeat interval will be beacon set bound. The list of beacons included in the set is available in the `beaconSets` field. I would imagine something like:

```json
"beaconSetUpdates": {
  "1": {
    "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC": {
      "beaconSets": [
        {
          "beaconSetId": "0x924b5d4cb3ec6366ae4302a1ca6aec035594ea3ea48a102d160b50b0c43ebfb5",
          "deviationThreshold": 0.1,
          "heartbeatInterval": 86400
        }
      ],
      "updateInterval": 30
    }
  },
  "3": {
    "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC": {
      "beaconSets": [
        {
          "beaconSetId": "0x924b5d4cb3ec6366ae4302a1ca6aec035594ea3ea48a102d160b50b0c43ebfb5",
          "deviationThreshold": 0.2,
          "heartbeatInterval": 86400
        }
      ],
      "updateInterval": 30
    }
  }
}
```

In the validation, we need to make sure that the beacon set present in this section has its counterpart in the `beaconSets` section.

**Comment by bbenligiray** [comment]
I don't think `beaconIds` is needed, that information is already present in https://github.com/API3-CTT/airseeker/issues/163

**Comment by amarthadan** [comment]
Issue description updated based on the [Slack discussion](https://api3workspace.slack.com/archives/C037NLX1R8T/p1658137012920379?thread_ts=1658072085.473819&cid=C037NLX1R8T).
