### ISSUE TITLE
Implement environment setup for testing

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airseeker-v1#170]
Even though we have E2E tests we from time to time need to test new Airseeker features so we need to set up an environment (prepare blockchain, run Airnode(s), etc.) to do it. It would be nice to have this at least semi-automated/scripted.

**Comment by acenolaza** [comment]
@amarthadan while planning how to acoomplish this I came up with the following list of steps that will be needed for running Airseeker locally for testing:

1. run a local eth node (hardhat node)
2. deploy DapiServer contract (with a script)
3. run [airnode-client docker image ](https://docs.api3.org/airnode/v0.8/grp-providers/tutorial/quick-deploy-container/)locally (with http signed gateway enabled) 
4. invoke airseeker function using serverless

This assumes that there will be an Airnode `config.json` file along with a `secrets.env` file prepared for serving price data from something like coingecko. Airseeker file will need to be updated with templates and endpoints that will work for that Airnode.

The only issue that I facing is that Airnode v0.7.5 won't support step #3. This feature has been [added to master](https://github.com/api3dao/airnode/pull/1352) and I think it will only be available in v0.8. Should we wait for that to be published? Should we complicate things a bit and deploy to AWS or GCP? Should we instead just have an express server that return dummy data? Ran out of ideas 🤭

**Comment by amarthadan** [comment]
I'd say no to using AWS/GCP, that would just complicate things :sweat_smile: 
I think having a simple dummy server (something similar to what we have for e2e tests right now) will be enough for now and once Airndoe v0.8 is released we can reuse that.
