### ISSUE TITLE
Add validation tests for beacon sets refinement rules

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airseeker-v1#190]
I noticed that those were not implemented when https://github.com/API3-CTT/airseeker/issues/163 and https://github.com/API3-CTT/airseeker/issues/164 were being done.

**Comment by acenolaza** [comment]
So [this](https://github.com/api3dao/airseeker/blob/166-update-beacon-sets-implementation/src/validation.ts#L43-L58) validation is tested by [this](https://github.com/api3dao/airseeker/blob/166-update-beacon-sets-implementation/src/validation.test.ts#L62-L80) test and [this](https://github.com/api3dao/airseeker/blob/166-update-beacon-sets-implementation/src/validation.ts#L294-L304) other validation by [this](https://github.com/api3dao/airseeker/blob/166-update-beacon-sets-implementation/src/validation.test.ts#L185-L204) other test but I did miss to test [this one](https://github.com/api3dao/airseeker/blob/166-update-beacon-sets-implementation/src/validation.ts#L249-L264). Good catch!
