### ISSUE TITLE
Change E2E tests to use Airseeker as a service

### ISSUE THREAD

**Issue by umersin61** [api3dao/airseeker-v1#214]
Currently, airseeker.feature.ts is importing the main() function to run the Airseeker for each test.

This change should be that Airseeker is started as a pm2 service and there is a single sleep() period for each test to wait for one Airseeker cycle to finish after the contracts are re-deployed.  (We can experiment with how long the sleep should be, probably 10-15 seconds)

**Comment by amarthadan** [comment]
I don't really think this will bring much anymore. See https://github.com/api3dao/airseeker/issues/161

**Comment by acenolaza** [comment]
> I don't really think this will bring much anymore. See https://github.com/api3dao/airseeker/issues/161

I agree. We should close this issue @umersin61
