### ISSUE TITLE
Switch from Serverless to Terraform in Airseeker

### ISSUE THREAD

**Issue by umersin61** [api3dao/airseeker-v1#215]
But still executing on serverless services.

Probably using Airnode's TF files as a template (so we can easily support GCP and AWS).

**Comment by bbenligiray** [comment]
I suspect that we shouldn't do this

**Comment by acenolaza** [comment]
@amarthadan has just [removed](https://github.com/api3dao/airseeker/pull/205/files?show-deleted-files=true&show-viewed-files=true&file-filters%5B%5D=) all terraform files form Airseeker so I'm guessing this issue is no longer relevant

**Comment by amarthadan** [comment]
As far as I remember this was about rewriting the current serverless setup as TF recipes. Not sure that's still the plan. @aquarat

**Comment by aquarat** [comment]
Sorry, just saw this while refining issues.

I think this needs to happen because Serverless only properly supports Lambda. Support for Azure and GCP appear to be broken (the last time I tried neither worked). The plan was to have two Airseekers; one on GCP and one on AWS.

**Comment by bbenligiray** [comment]
I recently told @aTeoke that Airseeker (with direct API calls) should be the first thing to be folded into Airnode v1 (based on BYOG revealing that Airkeeper is not good enough for the API providers to run as a back up). So this would be duplicating that work.

**Comment by aquarat** [comment]
Thanks @bbenligiray, I forgot about that/didn't appreciate the timeline. Let's close this issue then with that in mind.
