### ISSUE TITLE
Allow retrieval of signed gateway URLs from ChainAPI's API

### ISSUE THREAD

**Issue by aquarat** [api3dao/airseeker-v1#234]
Relates to #233

**Comment by vponline** [comment]
Once this is done Airseeker will also no longer need the signed gateway api key field (will be removed from Airnode in v0,10)

**Comment by aquarat** [comment]
Closing and recreating in operations as we will need these URLs in the operations database (for OEV and more generally for testing remote Airnodes I would think).
