### ISSUE TITLE
Create testing/dev beaconSet

### ISSUE THREAD

**Issue by acenolaza** [api3dao/airseeker-v1#241]
API3 Market team requires a testing/dev beaconSet. Here's the slack discussion about this: https://api3workspace.slack.com/archives/C037NLX1R8T/p1663330087379479

Tasks to be performed:

1. pick 3 random beacons from amberdata (let's say eth/usd, btc/usd and matic/usd)
2. create a beaconSet out of these 3
3. modify the current deployed airseeker.json file locally
4. run airseeker locally
5. deploy airseeker to aws with the new changes

**Comment by aquarat** [comment]
Closing as this was done (well done Santiago), see https://github.com/api3dao/operations/blob/main/data/beaconSets/stable_usd.json
