### ISSUE TITLE
Allow Airseeker to directly retrieve API data

### ISSUE THREAD

**Issue by aquarat** [api3dao/airseeker-v1#250]
Currently Airseeker calls a remote HTTP signed data gateway in order to retrieve signed API responses. 

We'd like Airseeker to have the ability to call an API directly and sign the result with the existing Airseeker mnemonic.

This will practically create a hybrid between Airseeker and Airkeeper in terms of functionality.

This should be implemented as a `method` in the trigger configuration, for instance:
```json
  "triggers": {
    "dataFeedUpdates": {
      "1": {
        "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC": {
          "beacons": [
            {
              "beaconId": "0xbc80cbd7a8b8180e11d189a8334814a44a69c4d083b31305ecf67a3a3ea0fd9a",
              "deviationThreshold": 0.1,
              "heartbeatInterval": 86400
              "method": "direct"
            },
```
`method` should be capable of supporting other arbitrary retrievers through a common interface, eg.
```typescript
// something like...
interface DirectRequest {
  template: Id<Template>;
}

interface GatewayRequest extends DirectRequest {
  gateways: Gateway[];
}

interface Request {
  (request: DirectRequest | GatewayRequest): Promise<SignedData>
}

export const makeSignedDataGatewayRequests = async (
  gateways: Gateway[],
  template: Id<Template>
): Promise<SignedData> => {};
```

Methods could be:
- `direct` - call the API directly
- `v0.6.5` - call the remote gateway using an adapter for v0.6.5 Airnode
- `v0.9.0` - etc.

The above will require Airseeker to have access to the OIS. This could be included at the top level of `airseeker.json` as an array of OISes:
```json
{
  "triggers": {},
  "templates": {},
  "oises": [
    {
      "oisFormat": "1.1.1",
      "title": "<FILL_*>",
      "version": "<FILL_*>"
    }
  ]
}
```
Airseeker should search the available OISes for the first OIS that contains a matching endpoint and use the associated details to execute the direct call. The API response data should be signed with the Airseeker's mnemonic.

This will also require Airseeker to include an `apiCredentials` field in the config file.
Mnemonic derivation should be done up-front (like Airnode's deployer) to reduce duplication of processor usage.

**Comment by bbenligiray** [comment]
The `airseeker.json` additions should be `ois`, `apiCredentials`, `endpoints` after [`airkeeper.json`](https://github.com/api3dao/airkeeper/blob/main/config/airkeeper.example.json)
