### ISSUE TITLE
Investigate persisting double transaction issue

### ISSUE THREAD

**Issue by metobom** [api3dao/airseeker-v1#382]
See [transaction 1](https://zkevm.polygonscan.com/tx/0xb9eaeaa1613decc7200a9f3ff6e152acd0cf635911900175cc35accc6602f4bc) and [transaction 2](https://zkevm.polygonscan.com/tx/0x78924d0aad6588e6dafa547bbf8ab30f804254203ae38fd105601d688b24bfb9).

**Comment by bbenligiray** [comment]
Since we're using issues to represent tasks, they need to be formatted to describe tasks. `Double transaction issue persists` is not a task.

**Comment by metobom** [comment]
As a result of @bdrhn9's [investigations](https://api3workspace.slack.com/archives/C043YH02PGQ/p1683765841224479?thread_ts=1683740490.082029&cid=C043YH02PGQ), the problem was sourced by zkEVM's block explorer and our updates were not duplicates. Closing this @acenolaza.

**Comment by acenolaza** [comment]
This was actually handled by @bdrhn9 so I'm reassigning it to him so he gets all the credit 😄
