### ISSUE TITLE
Fetch gateway URLs during runtime

### ISSUE THREAD

**Issue by metobom** [api3dao/airseeker-v1#442]
Currently, Airnode signed gateway URL changes require Airseekers to be redeployed. Would it be possible to fetch gateways from the database or through an endpoint every cycle?

**Comment by metobom** [comment]
Related to [this](https://github.com/api3dao/operations-database/issues/385) issue.

**Comment by bbenligiray** [comment]
The service that provides the gateway URLs becomes a single point of failure so this sounds like a bad idea
