### ISSUE TITLE
Improve sponsor wallet filtering

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airseeker-v1#446]
Currently, sponsor wallet balances are fetched at the beginning of the coordinator, and the sponsor wallets that have exactly zero balance are filtered out to reduce the Airseeker load. Self-funded sponsor wallets update until the funds run out, but the funds leave some dust instead of running out completely, and the filtering strategy isn't suited to address this.

Proposed method:
- At the start of the coordinator, generate a random wallet (to use as `airnode`), and call `estimateGas()` with it to estimate the gas of initializing a Beacon
- As the second step, fetch the gas price as described by the gas price strategy
- Filter the sponsor wallets whose balances are lower than the multiplication of the above two values

**Comment by bbenligiray** [comment]
@metobom this is not Phase 2 so I wanted to move it o Post-phase 2, but I see that there is no Post-phase 2 milestone in the airseeker repo. It's annoying to have to add the same milestones to all repos that are in this view so maybe there is a better way of implementing this.

**Comment by acenolaza** [comment]
> call estimateGas() with it to estimate the gas of initializing a Beacon

@bbenligiray does this mean to simulate a call to [updateBeaconWithSignedData](https://github.com/api3dao/airnode-protocol-v1/blob/main/contracts/api3-server-v1/BeaconUpdatesWithSignedData.sol#L26) with random data?

UPDATE: I guess it would be something like [this](https://github.com/api3dao/airseeker/commit/4614650a45da552294ac41fa47de77cf2b84e596#diff-ac6a312c9e24133a7c95de8d3425130b31ffb3f35d99201839b67c76fac94770R77-R119)

If this is the desired approach then I'd like to share some thoughts:
1. zksync does not seem to be happy about calling `estimateGas` with `VoidSigner` and fails with the following error message: `{"jsonrpc":"2.0","error":{"code":3,"message":"invalid sender. can't start a transaction from a non-account","data":"0x"},"id":44}`
2. should we just connect the `api3ServerV1` contract to the `sponsorWallet` when calling `udpateBeaconWithSignedData` using `estimateGas` and if it fails then we treat the sponsor wallet as not having enough funds?
3. should we also add the `gasTarget` properties returned by calling `node.getGasPrice()` to the `estimateGas.udpateBeaconWithSignedData` call?

**Comment by bbenligiray** [comment]
> UPDATE: I guess it would be something like [this](https://github.com/api3dao/airseeker/commit/4614650a45da552294ac41fa47de77cf2b84e596#diff-ac6a312c9e24133a7c95de8d3425130b31ffb3f35d99201839b67c76fac94770R77-R119)

Not sure what I'm looking at here but I can explain again
```
const randomWallet = ethers.Wallet.createRandom();
const templateId = ethers.constants.HashZero;
const decodedBeaconData = {value: 123, timestamp: 123};
const {timestamp, data, signature} = signBeaconData(randomWallet, decodedBeaconData, templateId);
// it doesn't matter which wallet we connect with below
const gaslimit = api3ServerV1.connect(randomWallet).estimateGas.updateBeaconWithSignedData(
        randomWallet.address,
        templateId,
        timestamp,
        data,
        signature
    )
```
So the idea is that we'll need to provide a valid signature to the blockchain provider here and we don't want to give them a valid signature signed by the actual Airnode address, the blockchain provider can potentially use that to update the mock Beacon with mock values. This doesn't use VoidSigner at all.

> should we just connect the api3ServerV1 contract to the sponsorWallet when calling udpateBeaconWithSignedData using estimateGas and if it fails then we treat the sponsor wallet as not having enough funds?

Are you sure that `estimateGas` fails when the connected wallet is underfunded? (I'm not but I doubt it.)

> should we also add the gasTarget properties returned by calling node.getGasPrice() to the estimateGas.udpateBeaconWithSignedData call?

The main downside I can see with that is the gasTarget properties may require more than 1 RPC call to be made, but the result will still not be exact as being able to execute a single Beacon update doesn't guarantee that the sponsor wallet is not funded enough (what if all triggers are Beacon sets?) This is only a small gripe though, I don't see why not otherwise.

**Comment by acenolaza** [comment]
> This doesn't use VoidSigner at all.

Right, I was just trying to see if there was a way to call `estimateGas()` without first connecting the contract with an actual wallet instance. I can just connect the sponsorWallet instance and problem solved.

> Are you sure that `estimateGas()` fails when the connected wallet is underfunded? (I'm not but I doubt it.)

When overriding the `gasPrice` on the `estimageGas()` call then it seems to do some checks on the connected signer wallet and reverts with either INSUFFICIENT_FUNDS or with UNPREDICTABLE_GAS_LIMIT when connected wallet balance is zero o not enough.

`insufficient funds for intrinsic transaction cost [ See: https://links.ethers.org/v5-errors-INSUFFICIENT_FUNDS ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":45,\"error\":{\"code\":-32000,\"message\":\"insufficient funds for gas * price + value: address 0x9c2914C0AEB698f618d0Cd8D98F88a44eAF31B16 have 0 want 682950626100000000\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x32e23fdaa\",\"from\":\"0x9c2914c0aeb698f618d0cd8d98f88a44eaf31b16\",\"to\":\"0x3dec619dc529363767dee9e71d8dd1a5bc270d76\",\"data\":\"0x1a0a0b3e000000000000000000000000cbafe20c0b2cd33dcb7d365bea52e44be68207a7c5cc878cf5df3d2f3e64ad970f379f48131e163ea699d913673ccc8837c15b600000000000000000000000000000000000000000000000000000000064f9baca00000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000e8b1b0deabb300000000000000000000000000000000000000000000000000000000000000416bed337adbac44ea60d7734ad877f53ad72ca47fa592658f603d8b7197602a2d0cf65fa2b00ec4bfa97a42499b91331094e3a0777ef45c1c65ff57ae1e452caa1c00000000000000000000000000000000000000000000000000000000000000\"}],\"id\":45,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rpc.reblok.io/eth?apikey="}, method="estimateGas", transaction={"from":"0x9c2914C0AEB698f618d0Cd8D98F88a44eAF31B16","gasPrice":{"type":"BigNumber","hex":"0x032e23fdaa"},"to":"0x3dEC619dc529363767dEe9E71d8dD1A5bc270D76","data":"0x1a0a0b3e000000000000000000000000cbafe20c0b2cd33dcb7d365bea52e44be68207a7c5cc878cf5df3d2f3e64ad970f379f48131e163ea699d913673ccc8837c15b600000000000000000000000000000000000000000000000000000000064f9baca00000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000e8b1b0deabb300000000000000000000000000000000000000000000000000000000000000416bed337adbac44ea60d7734ad877f53ad72ca47fa592658f603d8b7197602a2d0cf65fa2b00ec4bfa97a42499b91331094e3a0777ef45c1c65ff57ae1e452caa1c00000000000000000000000000000000000000000000000000000000000000","accessList":null}, code=INSUFFICIENT_FUNDS, version=providers/5.7.2)`

`cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32603,\"message\":\"gas required exceeds allowance 0\"},\"id\":45}","error":{"code":-32603},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x23702cd0d2\",\"from\":\"0x9c2914c0aeb698f618d0cd8d98f88a44eaf31b16\",\"to\":\"0x3dec619dc529363767dee9e71d8dd1a5bc270d76\",\"data\":\"0x1a0a0b3e000000000000000000000000cbafe20c0b2cd33dcb7d365bea52e44be68207a7568c21e26f19c488eb410e7b7b7d0a36795a323fa65bb4dec1e3c496988f05d00000000000000000000000000000000000000000000000000000000064f9bacb00000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000002000000000006ce03655547ab795c07bf8ddf9330886f90ca8b564fdf033052b4f000000000000000000000000000000000000000000000000000000000000004194513288db72f76a6bc31e779a638be4b285d5f881d24627bac23a108995372d758027d408013cb8d4f3222386e009ac177a4157bca32d02437999e8ee82907b1c00000000000000000000000000000000000000000000000000000000000000\"}],\"id\":45,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rpc.reblok.io/moonbeam?apikey="}, method="estimateGas", transaction={"from":"0x9c2914C0AEB698f618d0Cd8D98F88a44eAF31B16","gasPrice":{"type":"BigNumber","hex":"0x23702cd0d2"},"to":"0x3dEC619dc529363767dEe9E71d8dD1A5bc270D76","data":"0x1a0a0b3e000000000000000000000000cbafe20c0b2cd33dcb7d365bea52e44be68207a7568c21e26f19c488eb410e7b7b7d0a36795a323fa65bb4dec1e3c496988f05d00000000000000000000000000000000000000000000000000000000064f9bacb00000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000002000000000006ce03655547ab795c07bf8ddf9330886f90ca8b564fdf033052b4f000000000000000000000000000000000000000000000000000000000000004194513288db72f76a6bc31e779a638be4b285d5f881d24627bac23a108995372d758027d408013cb8d4f3222386e009ac177a4157bca32d02437999e8ee82907b1c00000000000000000000000000000000000000000000000000000000000000","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)`

I couldn't find anything about this check in the ethers.js docs and as usual with this library, one can call estimateGas() in many different ways:
1. provider.estimateGas(tx)
2. sponsorWallet.estimateGas(tx)
3. api3ServerV1.estimateGas.someFunctionName()
each probably behaving in a slightly different manner. For the purpose of this issue I'll just go ahead without overriding the gasPrice but I might still override the gasLimit just to make the estimate call closer to the real call.

**Comment by bbenligiray** [comment]
I would not override anything. It would only make sense if the contract implementation depended on `tx.gasprice` or `tx.gaslimit`.

**Comment by bbenligiray** [comment]
btw I think you should refer to `eth_estimateGas` rather than ethers (though it probably maps one to one)
