### ISSUE TITLE
Do not use multicall for individual Beacon updates

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airseeker-v1#449]
This adds an unnecessary gas cost overhead for individual Beacon updates, which is quite important for self-funded feeds

**Comment by bbenligiray** [comment]
@metobom same with https://github.com/api3dao/airseeker/issues/448#issuecomment-1672779457

**Comment by acenolaza** [comment]
@bbenligiray at first I understood that we should not use `tryMulticall` on updateBeacons() [when the count of update calldatas is equal to 1](https://github.com/api3dao/airseeker/compare/main...449-update-single-beacon-without-multicall) but after re-reading the title and description on the issue I'm now thinking that the expected change is to just remove the `tryMulticall` altogether from `updateBeacons()`. Is this right?

**Comment by bbenligiray** [comment]
> at first I understood that we should not use tryMulticall on updateBeacons() [when the count of update calldatas is equal to 1](https://github.com/api3dao/airseeker/compare/main...449-update-single-beacon-without-multicall)

This is right

If there are 11 Beacons to be updated and we're updating them in batches of 10, we can also omit the `tryMulticall()` of the second batch with a single Becaon update. It feels like this would also reduce code duplication in your implementation.
